### PR TITLE
pg: add support for registering custom types at runtime

### PR DESCRIPTION
**Pull request by Bogdanp**
I use custom types and domains a bunch with Postgres, but, without a way to register custom types at runtime, db-lib makes it quite hard to use them day-to-day so I wanted to bring this improvement up for discussion. 

I limited the change to Postgres since, AFAIK, it's the only one of the databases that db-lib supports with a feature like custom types and domains.

Here's a self-contained example that demonstrates the issue:

```racket
#lang racket/base

(require db)

(define conn
  (postgresql-connect
   #:database "postgres"
   #:user "bogdan"))

(query-exec conn "drop domain if exists cents")
(query-exec conn "create domain cents as integer check(value > 0 and value < 100000000)")
(query-exec conn "create temporary table test(val cents)")
(query-exec conn "insert into test values($1)" 10)
```

This results in the following error:

```
; query-exec: unsupported type
;   typeid: 1636764
; Context:
;  /Applications/Racket v7.6/collects/db/private/generic/interfaces.rkt:363:0 error/unsupported-type
;  /Applications/Racket v7.6/collects/db/private/generic/prepared.rkt:90:0 apply-type-handlers
;  /Applications/Racket v7.6/collects/db/private/generic/prepared.rkt:70:4 bind method in prepared-statement%
;  /Applications/Racket v7.6/collects/db/private/generic/functions.rkt:148:0 query-exec
;  /Users/bogdan/tmp/t.rkt:1:1 [running body]
```

I'm aware that I can work around this by changing the insert statement to explicitly cast `$1` to an integer, but that doesn't help if I'm using an ORM and it just doesn't feel right.

With this change, the following code works as expected:

```racket
#lang racket/base

(require db
         db/private/postgresql/dbsystem)

(define conn
  (postgresql-connect
   #:database "postgres"
   #:user "bogdan"))

(query-exec conn "drop domain if exists cents")
(query-exec conn "create domain cents as integer check(value > 0 and value < 100000000)")

(register-custom-type!
 (query-value conn "select 'cents'::regtype::oid")
 (lambda (buf start end)
   (integer-bytes->integer buf #t start end))
 (lambda (_f n)
   (integer->integer-bytes n 4 #t #t)))

(query-exec conn "create temporary table test(val cents)")
(query-exec conn "insert into test values($1)" 10)
(query-value conn "select * from test")
```

I'd be happy to carry this forward and add tests and documentation if you think this is a change worth making.

### CODE REVIEW

**Comment by rmculpepper** [comment]
I think this would be a good feature, but it's complicated. Here are some of my thoughts:

The mapping of typeids to their descriptions should not be global, since connections to different servers could see colliding typeids. It would make the most sense to store a mapping in each connection, but the current prepared statement implementation expects the dbsystem to have the type readers and writers, and it would be unpleasant to change that. One solution would be to have each connection have its own dbsystem object with a mutable typeid table (and maybe use the current singleton dbsystem when the table is empty, as an optimization).

The base type of a domain type is available via the `typbasetype` field of `pg_type`. It would make sense to fetch that and use the base type's read and write functions automatically. Additional wrapping could be layered on top as conversions to/from the Racket representation of the base type. I really don't want to expose the low-level reader and writer interfaces (eg, `buf start end`) to users.

Keeping the Racket-side mapping in sync with the server is difficult, especially given that domains can be created and dropped via SQL (executed by the current connection or by another) and that changes can be unwound by transaction rollback. I don't know any way to automatically keep the mapping correct without adding unacceptable overhead. So maybe a good compromise would be to assume no changes and require the user to explicitly request updates. The update method could allow the user to choose whether to specify the base type manually or have it automatically looked up.

**Comment by Bogdanp** [comment]
Thanks for the reply! I'll look at implementing a better version of this when I find some time in the coming weeks.

> Keeping the Racket-side mapping in sync with the server is difficult, especially given that domains can be created and dropped via SQL (executed by the current connection or by another) and that changes can be unwound by transaction rollback.

As a user, I would expect the onus to be on me to keep these mappings in sync.

> So maybe a good compromise would be to assume no changes and require the user to explicitly request updates. The update method could allow the user to choose whether to specify the base type manually or have it automatically looked up.

👍 to the user having to explicitly add/update/remove types.

> I really don't want to expose the low-level reader and writer interfaces (eg, buf start end) to users.

What about a simplified interface?

    reader : bytes? -> any/c
    writer : any/c -> bytes? 

I think this would give the user a lot of flexibility, while also allowing the underlying implementation to change. I can definitely live without this, though, so I'm happy to drop it if you think it's a bad idea.

**Comment by rmculpepper** [comment]
The approach I would prefer would be to register a domain type by specifying its base type and an optional pair of encode and decode functions that convert between the representation of the domain type and the representation of the base type. See `WRAP` in the `asn1` library for an instance of this approach; see the "Handing Unsupported Types" section for an example. (And the user can get the behavior you propose by claiming that `bytea` is the base type.)

We should also consider what would be necessary to support types created with `CREATE TYPE` in addition to `CREATE DOMAIN`. It would be preferable to have a single mechanism that handles both, if that's practical.

**Comment by rmculpepper** [comment]
I've added basic support for custom types. See the docs for `pg-custom-type`. I'll close this PR, but you can reopen it or open a bug if you have issues or feedback about the design.

**Comment by curtdutt** [comment]
I'm having trouble registering a citext[] array type.

I have the citext type working fine using the text reader.

(send conn pg-custom-type citext-id
                                    'citext
                                    'text)

However I can't figure out how to use the text-array reader because passing in the text-array reader complains about the wrong type in recv-array

  (pg-custom-type citext-id
                              'citext-array
                               'text-array)

recv-array: wrong element typeid: expected 25, got 17109


So I tried then to build my own recv-array based receiver but I can't seem to access that through the dbsystem class interface.

Either way perhaps pg-custom-type could allow registering an array with a base type somehow?

(send conn pg-custom-array-type citext-id
                                                      'citext-array
                                                      'text))

**Pull request closed without merging**
